### MANDATORY DEFINITIONS ###

data_directory: AI4U_sample2
obs_features:
  - EMA_mood
  - EMA_stress
input_features:
  - interactive1
  - interactive2
timestamp:
  absolute_datetime_column: DateTime
  relative_datetime_column: Timerels
  time_anchor: '2022-01-01 00:00:00'
  datetime_format: '%Y-%m-%d %H:%M:%S'
preprocessing:
  - time_smoothing:
      columns_to_smooth:
        - EMA_stress
      kernel_std_hours: 1.5
      kernel_width_hours: 4.0
      causal: true
train_test_split: 123
model: plrnn

### OPTIONAL DEFINITIONS ###

# Dataset

seq_len: 16
partial_missings_are_valid: true
tolerate_reduced_seq_len: true
data_dropout_to_level: null

# Training

batch_size: 32
batches_per_epoch: 0
num_epochs: 500
learning_rate: 0.001
lr_annealing: true

gradient_clipping: 10.0
model_save_step: last
info_save_step: 100

tf_alpha: 0.125

validation_len: 7
validation_prewarming: 0

### HYPERPARAMETER SEARCH DEFINITIONS ###

hyperparameters:
  learning_rate:
    - 0.001
    - 0.0005
  batch_size:
    - 16
    - 32

# combined_hyperparameters:
#   - seq_len: 16
#     num_epochs: 1000
#   - seq_len: 32
#     num_epochs: 2000